const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const $=id=>document.getElementById(id);let S=null,busy=false,rot=0;
async function api(action,data={}){const r=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,data,initData:tg?.initData||""})});const j=await r.json();if(!r.ok||j.error)throw Error(j.error||"Request failed");return j}
function page(id){document.querySelectorAll(".page").forEach(x=>x.hidden=true);$(id).hidden=false;window.scrollTo(0,0)}
function toast(t){const x=$("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function render(){if(!S)return;let b=+S.balance||0,p=Math.min(100,b),a=S.adsToday||0,ap=S.adProgress||0;$("balance").textContent=b.toFixed(2);$("wBalance").textContent=b.toFixed(2);$("spins").textContent=S.spins||0;$("prog").style.width=p+"%";$("progText").textContent=`${b.toFixed(2)} / 100 Birr`;$("left").textContent=b>=100?"✅ Withdrawal unlocked":`${Math.max(0,100-b).toFixed(2)} Birr left to withdraw`;$("ads").textContent=`${a} / 50`;$("adsSmall").textContent=`${a} / 50 ads`;$("adsBar").style.width=(a/50*100)+"%";$("adToSpin").textContent=`${ap} / 5`;$("spinBar").style.width=(ap/5*100)+"%";$("refSmall").textContent=`${S.referrals||0} referrals`;$("refs").textContent=S.referrals||0;$("refSpins").textContent=S.referralSpins||0;$("rank").textContent=S.rank?`#${S.rank}`:"—";$("wState").textContent=b>=100?"✅ UNLOCKED":"🔒 LOCKED";$("wNeed").textContent=b>=100?"Minimum reached.":"You need "+Math.max(0,100-b).toFixed(2)+" Birr more.";$("withdrawBtn").disabled=b<100||S.withdrawPending; $("adBtn").disabled=a>=50||busy;$("dailyBtn").disabled=!!S.dailyClaimed;$("dailyBtn").textContent=S.dailyClaimed?"✓ CLAIMED":"CLAIM REWARD";$("day").textContent=`DAY ${S.dailyDay||1}`;$("dailyReward").textContent=`+${S.dailySpinReward||1} SPIN`;$("streak").textContent=`🔥 ${S.streak||0} DAY STREAK`;$("refLink").textContent=S.refLink||"Loading...";renderTasks();renderHistory();renderMissions()}
function renderTasks(){const channels=S.tasks||[];$("tasksList").innerHTML=channels.map(t=>`<div class="card task"><div class="grow"><b>📢 ${t.name}</b><small>Reward: +1 Spin</small></div>${t.done?'<b class="done">✓ VERIFIED</b>':`<button onclick="openTask('${t.id}')">JOIN</button><button onclick="verifyTask('${t.id}')">VERIFY</button>`}</div>`).join("")}
function renderMissions(){$("missions").innerHTML=`<p>🎬 Watch 5 Ads — ${Math.min(S.adsToday||0,5)}/5 ${S.adsToday>=5?"✓ COMPLETED":""}</p><p>👥 Invite 1 Friend — ${Math.min(S.referrals||0,1)}/1 ${S.referrals>=1?"✓ COMPLETED":""}</p><p>📅 Daily check-in — ${S.dailyClaimed?"✓ COMPLETED":"Ready"}</p>`}
function renderHistory(){$("history").innerHTML=(S.history||[]).length?(S.history||[]).slice(0,20).map(x=>`<div class="row" style="padding:9px 0;border-bottom:1px solid #18253a"><span>${x.label}</span><b>${x.amount}</b></div>`).join(""):"📜 No transactions yet"}
async function init(){try{S=await api("init");render();$("loading").hidden=true;$("app").hidden=false}catch(e){$("loading").innerHTML="<b>⚠️</b><strong>Birr Spin</strong><span>"+e.message+"</span>"}}
async function spin(){if(busy||!S.spins)return toast("🎡 No spins available");busy=true;$("spinBtn").disabled=true;try{const j=await api("spin");rot+=1440+(j.rewardIndex||0)*40;$("wheel").style.transform=`rotate(${rot}deg)`;setTimeout(()=>{S=j.state;render();$("modalReward").textContent="+"+Number(j.reward).toFixed(2)+" Birr";$("modalTitle").textContent=j.free?"🎁 FREE SPIN!":"🎉 YOU WON!";$("modal").hidden=false;busy=false;$("spinBtn").disabled=false},4100)}catch(e){busy=false;$("spinBtn").disabled=false;toast("⚠️ "+e.message)}}
function closeModal(){$("modal").hidden=true}
async function watchAd(){if(busy)return;busy=true;$("adBtn").disabled=true;try{if(typeof window.show_11746054!=="function")throw Error("Monetag SDK is not ready");const result=await window.show_11746054({type:"end",ymid:String(S.telegramId),requestVar:"watch_ads",catchIfNoFeed:true});if(result?.reward_event_type==="non_valued")throw Error("Ad was not valued");const j=await api("adComplete",{event:result});S=j.state;render();toast(j.spinAdded?"🎉 +1 Spin":"✓ Ad completed")}catch(e){toast("⚠️ Ad not completed. "+e.message)}finally{busy=false;$("adBtn").disabled=(S?.adsToday||0)>=50}}
async function claimDaily(){try{S=(await api("daily")).state;render();toast("🎁 Daily reward claimed!")}catch(e){toast("⚠️ "+e.message)}}
function openTask(id){const t=(S.tasks||[]).find(x=>x.id===id);if(t?.url)window.open(t.url,"_blank")}
async function verifyTask(id){try{toast("⏳ CHECKING MEMBERSHIP...");S=(await api("verifyTask",{taskId:id})).state;render();toast("✓ VERIFIED +1 Spin")}catch(e){toast("⚠️ "+e.message)}}
async function copyRef(){await navigator.clipboard.writeText(S.refLink);toast("✓ COPIED")}
function shareRef(){const u=encodeURIComponent(S.refLink),t=encodeURIComponent("🇪🇹 Birr Spin — Spin • Earn • Withdraw");window.open(`https://t.me/share/url?url=${u}&text=${t}`,"_blank")}
async function withdraw(){if(S.balance<100)return;const phone=prompt("Telebirr phone/account number:");if(!phone)return;try{S=(await api("withdraw",{phone,amount:100})).state;render();toast("🟡 Withdrawal request sent")}catch(e){toast("⚠️ "+e.message)}}
init();